ALTER TABLE Usuarios
    ADD COLUMN IF NOT EXISTS Nome      text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS Sobrenome text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS Celular   text NOT NULL DEFAULT '';

ALTER TABLE Usuarios
    ALTER COLUMN Nome DROP DEFAULT,
    ALTER COLUMN Sobrenome DROP DEFAULT,
    ALTER COLUMN Celular DROP DEFAULT;
